#pragma once

#include <cstdint>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Z88DK MAP Loader — Stage 6.2
//
// Parses MAP files generated by zcc/z88dk linker.
// Format example:
//   _main                    = $0252 ; addr, public, ...
//   fp_c000_inner            = $01D1 ; addr, local, ...
//
// Format validation: rejects non-Z88DK files (e.g. old keyboard .map configs)
// by checking that the file contains the characteristic "= $" pattern.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Visibility
// ---------------------------------------------------------------------------

enum class MapSymbolVisibility
{
    Public,
    Local
};

// ---------------------------------------------------------------------------
// Parsed MAP symbol
// ---------------------------------------------------------------------------

struct MapSymbol
{
    std::string          name;
    uint16_t             address   = 0;
    MapSymbolVisibility  visibility = MapSymbolVisibility::Public;
    bool                 isAddress  = false;  // "addr" type in MAP
    // Source location (if present)
    std::string          sourceFile;
    int                  sourceLine  = 0;
};

// ---------------------------------------------------------------------------
// Parse result
// ---------------------------------------------------------------------------

struct MapLoadResult
{
    bool                     success      = false;
    std::string              errorMessage;
    std::vector<MapSymbol>   symbols;
    int                      parsedCount  = 0;
    int                      skippedLines = 0;
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

namespace MapLoader
{
    // Parse a MAP file from disk.
    // Returns success=true only if the file is a valid Z88DK MAP.
    // Old keyboard .map files will fail format validation and return
    // success=false with a descriptive errorMessage.
    MapLoadResult loadMapFile(const std::string &path);

    // Parse MAP content from a string (for testing).
    MapLoadResult parseMapContent(const std::string &content);

    // Derive MAP file path from ROM path (replace extension with .map).
    std::string mapPathFromRom(const std::string &romPath);
}
