V06X := ../../src
INCLUDES    := -I$(CORE_DIR)/../../src -I$(CORE_DIR)
SOURCES_C   := $(CORE_DIR)/libretro.c $(CORE_DIR)/boot/boots.c $(CORE_DIR)/boot/boot.c
SOURCES_V06X := $(addprefix $(V06X)/, board.cpp options.cpp debug.cpp \
    tv.cpp cadence.cpp filler.cpp hal.cpp resampler.cpp util.cpp \
    fsimage.cpp i8080.cpp memory.cpp sound.cpp utils_string.cpp)
SOURCES_CXX := $(SOURCES_V06X) \
	emulator_libretro.cpp \
    	libretro_main.cpp

